development:
  host: localhost
  adapter: postgresql
  database: check_availability_development
  pool: 5
  username: postgres
  password: access
  timeout: 5000

test:
  host: localhost
  adapter: postgresql
  database: check_availability_test
  pool: 5
  username: postgres
  password: access
  timeout: 5000